"""Add poster field to Restaurants

Revision ID: 66e1e5a4df53
Revises: 72a6c1dc4fa3
Create Date: 2023-06-29 10:37:49.659886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66e1e5a4df53'
down_revision = '72a6c1dc4fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster', sa.String(length=300), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurants', schema=None) as batch_op:
        batch_op.drop_column('poster')

    # ### end Alembic commands ###
